#! /usr/bin/php
<?php

declare(strict_types=1);

use JesusValera\Minicli\App;
use JesusValera\Minicli\IO\CliPrinter;

require __DIR__ . '/vendor/autoload.php';

if ('cli' !== php_sapi_name()) {
    exit();
}

$app = new App(new CliPrinter());

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getPrinter()->display("usage: minicli hello [ your-name ]");
});

$app->registerCommand('hello', function (array $argv) use ($app) {
    $name = isset ($argv[2]) ? $argv[2] : "World";
    $app->getPrinter()->display("Hello $name");
});

try {
    $app->runCommand($argv);
} catch (Exception $exception) {
    $app->getPrinter()->display($exception->getMessage());
}
