#! /usr/bin/php
<?php

declare(strict_types=1);

use JesusValera\Minicli\App;
use JesusValera\Minicli\Command\HelloController;
use JesusValera\Minicli\IO\CliPrinter;

require __DIR__ . '/vendor/autoload.php';

if ('cli' !== PHP_SAPI) {
    exit();
}

$printer = new CliPrinter();
$app = new App();

$app->registerCommand('help', fn() => $printer->display('usage: minicli hello [ your-name ]'));

$app->registerController('hello', new HelloController($printer));

try {
    $app->runCommand($argv);
} catch (Exception $exception) {
    $printer->display($exception->getMessage());
}
