#! /usr/bin/php
<?php

declare(strict_types=1);

use JesusValera\Minicli\App;
use JesusValera\Minicli\IO\CliPrinter;

require __DIR__ . '/vendor/autoload.php';

if ('cli' !== php_sapi_name()) {
    exit();
}

(new App(new CliPrinter()))->runCommand($argv);
